{% set name = "atproto" %}
{% set version = "0.0.55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atproto-{{ version }}.tar.gz
  sha256: 8074181cb4647e56476c05ab36e20ff599a00366d34094a76ccc77e46498d7dd

build:
  entry_points:
    - atp = atproto_cli:atproto_cli
    - atproto = atproto_cli:atproto_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.25.0,<0.28.0
    - typing_extensions >=4.8.0,<5
    - click >=8.1.3,<9
    - websockets >=12,<14
    - pydantic >=2.7,<3
    - libipld >=2.0.0,<4
    - dnspython >=2.4.0,<3
    - cryptography >=41.0.7,<44

test:
  imports:
    - atproto
  commands:
    - pip check
    - atp --help
    - atproto --help
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/MarshalX/atproto
  summary: The AT Protocol SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
